### PR TITLE
feat: add doc versioning

### LINKED ISSUE #3048: Doc Versioning
**This is a Feature Request**

**What would you like to be added**

Doc Versioning. 

Docsy makes it easy to do doc versioning, including the ability to display a banner on archived doc sites/versions: https://www.docsy.dev/docs/adding-content/versioning/

**Why is this needed**

To differentiate Jenkins X 3 docs from Jenkins X 2 docs.

**Comments**

This isn't an immediately pressing issue, but as Jenkins X 3 matures, it will be helpful and clarifying if the docs are versioned.

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes #3048

### CODE REVIEW

**Comment by ankitm123** [comment]
So the reason it fails is because we dont pull the v2 release branch, and only pull and build the hugo site off the master branch. There's a nice explanation [here](https://github.com/google/docsy/issues/114#issuecomment-516592637).

Going to read up on some of the alternatives.

**Comment by MarckK** [comment]
Logs:
Screenshot 2020-11-16 at 16 21 57

**Comment by jstrachan** [comment]
@ankitm123 lots of link errors....

```
     <a href="/docs/v3/about/how-it-works/#boot-job">boot job will push changes</a>
- ./tmp-website/docs-v3/index.html
  *  internally linking to /docs/v3/about/changes/, which does not exist (line 0)
     <a href="/docs/v3/about/changes/" title="what has changed">Whats new</a>
  *  internally linking to /docs/v3/about/how-it-works/, which does not exist (line 0)
     <a href="/docs/v3/about/how-it-works/" title="How Jenkins X works">How it works</a>
  *  internally linking to /docs/v3/about/overview/, which does not exist (line 0)
     <a href="/docs/v3/about/overview/" title="Overview of Jenkins X and its architecture">Architecture</a>
  *  internally linking to /docs/v3/about/what, which does not exist (line 0)
     <a href="/docs/v3/about/what" title="What is Jenkins X and why would I use it">What is Jenkins X?</a>
  *  internally linking to /docs/v3/develop/, which does not exist (line 0)
     <a href="/docs/v3/develop/" title="GCP with GKE">Developer Guides</a>
  *  internally linking to /docs/v3/develop/create-project/, which does not exist (line 0)
     <a href="/docs/v3/develop/create-project/" title="create quickstarts or import new repositories">Create Projects</a>
  *  internally linking to /docs/v3/getting-started/azure/, which does not exist (line 0)
     <a href="/docs/v3/getting-started/azure/" title="setup Jenkins X on Azure cloud with AKS">
            <img alt="Azure" src="/images/logo/azure.svg" style="float: none;">
          </a>
  *  internally linking to /docs/v3/getting-started/eks/, which does not exist (line 0)
     <a href="/docs/v3/getting-started/eks/" title="setup Jenkins X on Amazon cloud with EKS">
            <img alt="Amazon" src="/images/logo/aws.svg" style="float: none;">
          </a>
  *  internally linking to /docs/v3/getting-started/gke/, which does not exist (line 0)
     <a href="/docs/v3/getting-started/gke/" title="setup Jenkins X on Google Cloud with GKE">
            <img alt="Google" src="/images/logo/gcp.svg" style="float: none;">
          </a>
  *  internally linking to /docs/v3/getting-started/minikube/, which does not exist (line 0)
     <a href="/docs/v3/getting-started/minikube/" title="setup Jenkins X on your laptop">
            <img alt="Minkube" src="/images/logo/minikube.svg" style="float: none;">
          </a>
  *  internally linking to /docs/v3/getting-started/on-premise/, which does not exist (line 0)
     <a href="/docs/v3/getting-started/on-premise/" title="setup Jenkins X on any Kubernetes cluster without cloud resources">
            <img alt="On Premise" src="/images/logo/k8s.svg" style="float: none;">
          </a>
  *  internally linking to /docs/v3/getting-started/openshift/, which does not exist (line 0)
     <a href="/docs/v3/getting-started/openshift/" title="setup Jenkins X on OpenShift">
            <img width="397" height="66" alt="OpenShift" src="/images/logo/openshift.png" style="float: none;"> 
          </a>
- ./tmp-website/docs/resources/guides/extending-**/index.html
  *  internally linking to /docs/v3/about/extending, which does not exist (line 0)
     <a href="/docs/v3/about/extending">improved extending guide</a>
```

**Comment by jstrachan** [comment]
still lots of errors...
```
  *  linking to internal hash #customising-charts that does not exist (line 0)
     <a href="/docs/v3/develop/apps/#customising-charts">app customisation mechanism</a>
  *  linking to internal hash #customising-charts that does not exist (line 0)
     <a href="/docs/v3/develop/apps/#customising-charts">how to customise a chart</a>
  *  linking to internal hash #customising-charts that does not exist (line 0)
     <a href="/docs/v3/develop/apps/#customising-charts">app customisation mechanism</a>
  *  linking to internal hash #edit-secrets that does not exist (line 0)
     <a href="/docs/v3/guides/secrets/#edit-secrets">editing the pipeline token</a>
  *  linking to internal hash #editing-pipelines that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#editing-pipelines">edit any pipeline in any git repository</a>
  *  linking to internal hash #generate-step that does not exist (line 0)
     <a href="/docs/v3/about/how-it-works/#generate-step">how it works</a>
  *  linking to internal hash #git-operator that does not exist (line 0)
     <a href="/docs/v3/about/how-it-works/#git-operator">git operator</a>
  *  linking to internal hash #how-do-i-configure-the-ingress-domain-in-dev-staging-or-production that does not exist (line 0)
     <a href="/docs/v3/develop/faq/#how-do-i-configure-the-ingress-domain-in-dev-staging-or-production">override domain names</a>
  *  linking to internal hash #ide-support that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#ide-support">IDE</a>
  *  linking to internal hash #ide-support that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#ide-support">IDE tooling</a>
  *  linking to internal hash #import-an-existing-project that does not exist (line 0)
     <a href="/docs/v3/develop/create-project/#import-an-existing-project">import a repository</a>
  *  linking to internal hash #import-an-existing-project that does not exist (line 0)
     <a href="/docs/v3/develop/create-project/#import-an-existing-project">import a repository</a>
  *  linking to internal hash #import-secrets that does not exist (line 0)
     <a href="/docs/v3/guides/secrets/#import-secrets">import secrets</a>
  *  linking to internal hash #reference-guide that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#reference-guide">reference guide</a>
  *  linking to internal hash #upgrading-pipelines-and-helm-charts that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#upgrading-pipelines-and-helm-charts">update mechanism on all git repositories</a>
  *  linking to internal hash #upgrading-pipelines-and-helm-charts that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#upgrading-pipelines-and-helm-charts">upgrade your local copy with upstream changes</a>
  *  linking to internal hash #using-vault that does not exist (line 0)
     <a href="/docs/v3/guides/secrets/vault/#using-vault">follow these instructions</a>
  *  linking to internal hash #vault that does not exist (line 0)
     <a href="/docs/v3/guides/config/#vault">configure vault</a>
  *  linking to internal hash #why-does-jenkins-x-use-helmfile-template that does not exist (line 0)
     <a href="/docs/v3/develop/faq/#why-does-jenkins-x-use-helmfile-template">helmfile template</a>
htmlproofer 3.17.0 | Error:  HTML-Proofer found 61 failures!
```

btw I don't think the link checker cares about aliases; it barfs if the link isn't correct?

**Comment by jstrachan** [comment]
errors:
```
     <a href="/docs/v3/develop/create-project/#create-a-new-project-from-a-quickstart">create a new quickstart</a>
  *  linking to internal hash #create-a-new-project-from-a-quickstart that does not exist (line 0)
     <a href="/docs/v3/develop/create-project/#create-a-new-project-from-a-quickstart">create a new quickstart</a>
  *  linking to internal hash #customising-charts that does not exist (line 0)
     <a href="/docs/v3/develop/apps/#customising-charts">app customisation mechanism</a>
  *  linking to internal hash #customising-charts that does not exist (line 0)
     <a href="/docs/v3/develop/apps/#customising-charts">how to customise a chart</a>
  *  linking to internal hash #customising-charts that does not exist (line 0)
     <a href="/docs/v3/develop/apps/#customising-charts">app customisation mechanism</a>
  *  linking to internal hash #edit-secrets that does not exist (line 0)
     <a href="/docs/v3/guides/secrets/#edit-secrets">editing the pipeline token</a>
  *  linking to internal hash #editing-pipelines that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#editing-pipelines">edit any pipeline in any git repository</a>
  *  linking to internal hash #generate-step that does not exist (line 0)
     <a href="/docs/v3/about/how-it-works/#generate-step">how it works</a>
  *  linking to internal hash #git-operator that does not exist (line 0)
     <a href="/docs/v3/about/how-it-works/#git-operator">git operator</a>
  *  linking to internal hash #how-do-i-configure-the-ingress-domain-in-dev-staging-or-production that does not exist (line 0)
     <a href="/docs/v3/develop/faq/#how-do-i-configure-the-ingress-domain-in-dev-staging-or-production">override domain names</a>
  *  linking to internal hash #ide-support that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#ide-support">IDE</a>
  *  linking to internal hash #ide-support that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#ide-support">IDE tooling</a>
  *  linking to internal hash #import-an-existing-project that does not exist (line 0)
     <a href="/docs/v3/develop/create-project/#import-an-existing-project">import a repository</a>
  *  linking to internal hash #import-an-existing-project that does not exist (line 0)
     <a href="/docs/v3/develop/create-project/#import-an-existing-project">import a repository</a>
  *  linking to internal hash #import-secrets that does not exist (line 0)
     <a href="/docs/v3/guides/secrets/#import-secrets">import secrets</a>
  *  linking to internal hash #reference-guide that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#reference-guide">reference guide</a>
  *  linking to internal hash #upgrading-pipelines-and-helm-charts that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#upgrading-pipelines-and-helm-charts">update mechanism on all git repositories</a>
  *  linking to internal hash #upgrading-pipelines-and-helm-charts that does not exist (line 0)
     <a href="/docs/v3/develop/pipeline-catalog/#upgrading-pipelines-and-helm-charts">upgrade your local copy with upstream changes</a>
  *  linking to internal hash #using-vault that does not exist (line 0)
     <a href="/docs/v3/guides/secrets/vault/#using-vault">follow these instructions</a>
  *  linking to internal hash #vault that does not exist (line 0)
     <a href="/docs/v3/guides/config/#vault">configure vault</a>
  *  linking to internal hash #why-does-jenkins-x-use-helmfile-template that does not exist (line 0)
     <a href="/docs/v3/develop/faq/#why-does-jenkins-x-use-helmfile-template">helmfile template</a>
htmlproofer 3.17.0 | Error:  HTML-Proofer found 61 failures!
```

**Comment by borntorock** [comment]
The suffix URL for the v3 docs is being served at `{URL}/docs-v3/` and for JX v2 at `{URL}/docs/`. Is this the behaviour we want and not the opposite?

I mean the v2 docs being served at `{URL}/docs-v2/` and the latest JX v3 docs being served at `{URL}/docs`.

**Pull request merged**
