### PR TITLE
fix(menu): expand sidebar menu by default

### PR DESCRIPTION
**Pull request by hervelemeur**
# Description

Expand sidebar menu by default in order to see directly where to look for a particular section instead of having to click on each of them

# Checklist:

- [X] I have mentioned the appropriate type(scope), as referenced [here](
) in the commit message and PR title for the semantic checks to pass.
- [X] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [X] Any dependent changes have already been merged.

### CODE REVIEW

**Comment by rawlingsj** [comment]
@hervelemeur can you rebase this PR please, that will enable the preview environment.

**Comment by jstrachan** [comment]
@hervelemeur love this change thanks! 

if we ever figure out how to do it - it'd be awesome on the very first docs page to only expand 1 level deep - e.g. this page https://jx-docs-jx-jenkins-x-jx-docs-pr-3146.dev.jenkins-x.me/v3/ though any child page the UX is much nicer - e.g. [developing](https://jx-docs-jx-jenkins-x-jx-docs-pr-3146.dev.jenkins-x.me/v3/develop/) or [admin](https://jx-docs-jx-jenkins-x-jx-docs-pr-3146.dev.jenkins-x.me/v3/admin/) pages

**Comment by hervelemeur** [comment]
> it'd be awesome on the very first docs page to only expand 1 level deep - e.g. this page [https://jx-docs-jx-jenkins-x-jx-docs-pr-3146.dev.jenkins-x.me/v3/](https://jx-docs-jx-jenkins-x-jx-docs-pr-3146.dev.jenkins-x.me/v3/)

@jstrachan an hacky way of doing almost this could be to simulate a click on https://jenkins-x.io/v3/about/ which would expand only the "about" section of the menu.

**Pull request merged**
