### PR TITLE
docs: tiny edits

### PR DESCRIPTION
**Pull request by MarckK**

### CODE REVIEW

**Comment by MarckK** [comment]
Double checking that we do demand that contributors to the docs sign DCO.  ;)

**Comment by MarckK** [comment]
@ankitm123 can you approve this for me? I want to see if it merges with no problem, even without the commit signed.

**Comment by ankitm123** [comment]
We dont have the requirement for signing commits yet, so pretty sure, it will pass. However, this should be implemented :)

**Pull request merged**
