### PR TITLE
chore: update supported k8s versions

### PR DESCRIPTION
**Pull request by Skisocks**
# Description

Updating the versions of K8s supported by JX

# Checklist:

- [ ] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ ] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ ] Any dependent changes have already been merged.

### CODE REVIEW

**Comment by msvticket** [comment]
We don't support 1.21 and 1.22 anymore. 

> Starting from the v0.41.x release of Tekton: Kubernetes version 1.23 or later

https://github.com/tektoncd/pipeline#required-kubernetes-version

**Review by msvticket — CHANGES_REQUESTED** [review]
Why ~ and not &ndash;?

**Comment by Skisocks** [comment]
> Why ~ and not –?

Not reason in particular :)

**Review by msvticket — APPROVED** [review]

**Pull request merged**
