### PR TITLE
docs: add consolidate addons and apps coding phase 2 doc

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

cc @MarckK

### CODE REVIEW

**Comment by MarckK** [comment]
Thank you for the PR for the blog post, @nodece!

Here are the logs:
Screenshot 2020-07-27 at 17 53 36

**Comment by nodece** [comment]
@MarckK I tried to merge upstream master to my branch.  I not sure if work.

**Comment by MarckK** [comment]
Hi @nodece, Thank you for your blog post! 😃

Logs:
```
- ./tmp-website/blog/2020/07/27/gsoc2020/index.html
  *  590:4: ERROR: Input contains prohibited control code point U+0008.
<pI also made a number of PR:</p>
   ^ (line 590)
htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!
Pipeline failed on stage 'build' : container 'step-htmlproofer'. The execution of the pipeline has stopped
```

**Comment by nodece** [comment]
@MarckK The error has been fix.

**Pull request merged**
