### PR TITLE
feat: Add spanish structure.

### PR DESCRIPTION
**Pull request by mmorejon**
Signed-off-by: Manuel Morejon <5578317+mmorejon@users.noreply.github.com>

### CODE REVIEW

**Comment by dennisnewel** [comment]
@mmorejon thanks for jumping in on another translation! I would suggest maybe tackling smaller sections at a time, like the Chinese translation, instead of the whole thing? there will likely be a constant stream of changes, and it could be difficult to try and keep the changes in sync across English and Spanish.

As a side note, the command references in `content/es/docs/reference/commands/`are actually generated from the source code and automatically updated via a script, so it's probably better to link to those pages instead of trying to keep them in sync

**Comment by mmorejon** [comment]
Thanks @dennisnewel  for the suggestions! I'm going to remove as much as possible except documentation section, at least for now. Where can I found the minimal structure possible?

**Comment by mmorejon** [comment]
I have deleted almost all the files. Let me know if should I remove more to keep just the base structure.

**Comment by dennisnewel** [comment]
looks like a great start. I'm not exactly sure what was done when the Chinese translation was first added, but as we were rearranging everything recently we just focused on having a structure for the pages that existed. Might be a better prompt for others to pitch in if they expect a Spanish translation and they get an English text :) we'll see

let's get it through the first level of testing so you can see it in the preview environment

/ok-to-test

**Comment by dennisnewel** [comment]
sorry @mmorejon something's borked with the build...i've asked for help internally (so far the logs are only accessible to the maintainers) as i can't figure out what's wrong. I'll try again once the issue has been fixed

**Comment by mmorejon** [comment]
Thanks @dennisnewel ! I'll be pending in case I can help.

**Comment by mauromorales** [comment]
@mmorejon I did some tests and managed to get your [build passing](https://dashboard-jx.jenkins-x.live/teams/jx/projects/jenkins-x/jx-docs/PR-2146/11) if I add certain content in the setup directory (see [commit](https://github.com/jenkins-x/jx-docs/pull/2146/commits/454ff87c0e1cb4c19a9f04ccc5041852828bbf8f)). I don't know hugo very well so I'm not entirely sure why you most have those files, maybe because they are being referenced? e.g. https://github.com/jenkins-x/jx-docs/pull/2130/files#diff-959edb48478a59e94007950e1bc9ca37R13

**Comment by dennisnewel** [comment]
thanks @mauromorales! unfortunately @mmorejon can't see the UI :) but it's awesome you found a solution for the problem. 
My best guess is that hugo tried to build up some list of pages, and not being able to find some where expected, it threw a nil exception...

would you be able to push your changes to the spanish-structure branch on mmorejon/jx-docs? that should trigger a build of this PR and we should hopefully see things working

**Comment by mmorejon** [comment]
I've been translating more pages in the Getting Started section during the day and when I saw your comments I push it waiting a good results during the build but wasn't the case.
I'm going to wait for your files @mauromorales

**Comment by mauromorales** [comment]
@dennisnewel I'd need access to @mmorejon's fork in order to push there. All I did was add the english version files so maybe you can just do the same locally. Here's the list: https://github.com/mauromorales/jx-docs/commit/bc5da96e3e0b2479cf1aec08c0b127d192d97f43

Basically, I just made a copy of the `boot`, `create-cluster` and `install` directories that are inside [content/en/docs/getting-started/setup](https://github.com/jenkins-x/jx-docs/tree/master/content/en/docs/getting-started/setup) into the `es` path.

**Comment by mmorejon** [comment]
Now works perfect! I was missing boot folder. 
Thanks @mauromorales !

**Comment by mauromorales** [comment]
@mmorejon seems like your last push already passes the build!

**Comment by dennisnewel** [comment]
looking good :) 

/lgtm
/approve

**Pull request merged**
