### PR TITLE
cdCon cfp blog post proposal

### PR DESCRIPTION
**Pull request by zestyroxy**
I would like to add this post to the blog to promote cdCon cfp to the Jenkins X community. Thanks :)

### CODE REVIEW

**Comment by rawlingsj** [comment]
@zestyroxy ok great, preview is built and deployed but the blog isn't showing here https://jx-docs-jx-jenkins-x-jx-docs-pr-3243.dev.jenkins-x.me/blog/ yet because the date is for tomorrow (hugo does some automatic thing to hide future posts) https://github.com/jenkins-x/jx-docs/pull/3243/files#diff-4d1f490f9a63a9880c0730c8902217d7fe9e2d982a317369996fc6c92d25e7bdR3

One other thing is I think we are missing this image https://github.com/jenkins-x/jx-docs/pull/3243/files#diff-4d1f490f9a63a9880c0730c8902217d7fe9e2d982a317369996fc6c92d25e7bdR46 if you don't mind adding that and changing the date of the blog to today then we should see the preview of it.

**Comment by zestyroxy** [comment]
I added the image here yesterday: https://github.com/jenkins-x/jx-docs/pull/3244 but it needs approval I believe.
 And will the preview work now that it's today?

**Pull request merged**
