### PR TITLE
Include Homebrew

### PR DESCRIPTION
**Pull request by tgelpi**
jenkins-x/homebrew-jx is the homebrew repo for installing the jx client for Jenkins X

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Checklist:

- [ ] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ ] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ ] Any dependent changes have already been merged.

### CODE REVIEW

**Review by msvticket — CHANGES_REQUESTED** [review]
As far as I can tell casks are note supported on linux. In any case this cask doesn't work on linux

**Comment by tgelpi** [comment]
@msvticket Removed brew (Linux) from doc as per your call out.

**Review by msvticket — CHANGES_REQUESTED** [review]
Since there already is a separate section for macOS I'd say you should put the homebrew instructions first in that section.

**Comment by tgelpi** [comment]
@msvticket Updated MacOS section as per your call out.

**Review by msvticket — APPROVED** [review]

**Pull request merged**
