### PR TITLE
fix: add missing repository url for the "jx gitops helmfile add" command

### PR DESCRIPTION
**Pull request by hervelemeur**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Checklist:

- [ ] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ ] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ ] Any dependent changes have already been merged.

### CODE REVIEW

**Comment by rawlingsj** [comment]
Hey @hervelemeur thanks for this. I'll double check in the morning but I think the `jx gitops helmfile resolve` command adds the repository because it's known in the version stream https://github.com/jenkins-x/jx3-versions/blob/cd78f23c3ff29d6964d54acd3686a3bb025c56c3/charts/repositories.yml#L53

**Comment by hervelemeur** [comment]
@rawlingsj here is the error I've got without it:

```
$ jx gitops helmfile add --chart k8s-at-home/oauth2-proxy  
error: failed to match prefix k8s-at-home with repositories from versionstream : no matching repository for for prefix k8s-at-home
```

**Comment by rawlingsj** [comment]
@hervelemeur ah - I wonder if you could try a `jx gitops upgrade` if you are on the latest version stream first please?  If that's it then we can add that to the docs as we'll need the latest oauth2 proxy default configs

**Comment by hervelemeur** [comment]
Not sure if I didn't gitops upgraded meanwhile, probably since I don't get any error now:
```
➜ helm repo remove k8s-at-home
"k8s-at-home" has been removed from your repositories
➜ jx gitops helmfile add --chart k8s-at-home/oauth2-proxy  
about to run: git add * in dir .
```

**Comment by hervelemeur** [comment]
Not needed anymore.

**Pull request closed without merging**
