### PR TITLE
chore: adding labs warning to all labs related documentation

### PR DESCRIPTION
**Pull request by vfarcic**
This PR adds the warning from the initial labs page to all the labs pages. That way, people will know that it is experimental and that the current labs are closed no matter whether they navigate through the left-hand navigation, or stumble upon one of the pages through, let's say, Google search.

### CODE REVIEW

**Comment by sharepointoscar** [comment]
@vfarcic and/or @hferentschik is this still relevant? I believe we have the verbiage on the Labs landing page already.

**Comment by hferentschik** [comment]
@sharepointoscar 

> is this still relevant? I believe we have the verbiage on the Labs landing page already.

Right, the warning is once on the landing page, but all other pages don't contain the warning. So if you don't read it on the landing page or if you even not come in via the landing page you might miss it. My guess is that the attempt here is to make sure that on each Labs related page it becomes clear that it was an experiment. 

Not sure really what to do. Happy to merge I guess. @ethangj wdyt? 

Personally I am wondering whether this documentation should be even there at all.

**Comment by hferentschik** [comment]
@vfarcic, technically is there a chance you can update the commit message to follow the conventional [commit message format](https://www.conventionalcommits.org/en/v1.0.0/)? Something like "chore: adding labs warning to all labs related documentation".

**Comment by vfarcic** [comment]
My bad... Sorry for that... It should be OK now.

**Comment by ethangj** [comment]
My opinion is that if the docs are gonna be live (which they already are), we need to be over the top with warnings so there's no chance at confusion.

**Pull request merged**
