### PR TITLE
docs: add rich event metadata

### LINKED ISSUE #2133: Add Google Event rich results
To make upcoming Jenkins X events show up more prominently in Google results, we can create a special JSON-LD file with event information and make Google aware of it.

More information here: https://developers.google.com/search/docs/data-types/event

### PR DESCRIPTION
**Pull request by karentobo**
Resolves #2133 by adding rich event metadata to one blog entry for Jenkins World and one event for FOSDEM.

I didn't use a JSON-LD file, but just added the metadata in two formats:

- The FOSDEM event supplies all values as metadata without affecting the visible content of our page.
- The Jenkins World event mixes the event data in with the visible content.

I'm a tester with automation skills and not at all a UI developer, so I'd love feedback to make this easier to copy/paste to other events.

### CODE REVIEW

**Comment by dennisnewel** [comment]
Nice. didn't realize we could just mark up the individual events. good catch

in terms of making things easier, we could probably create a shortcode (https://gohugo.io/templates/shortcode-templates/) that would take some part of the content as input and place it in the correct meta tags.
Another, more basic, option would be to just include a readme in the talks folder or something; a basic text file with something to copy-paste.

This looks good for now though, so let's try and get this out and we can tackle the shortcode/readme separately.

/ok-to-test

**Comment by dennisnewel** [comment]
not sure if it's a missing upstream merge? but this page http://jx-docs.jx-jenkins-x-jx-docs-pr-2148.jenkins-x.live/community/events/2019-12-dwjw/ is missing some meta data at the top, which is likely the cause of the missing styling

**Comment by karentobo** [comment]
> not sure if it's a missing upstream merge? but this page http://jx-docs.jx-jenkins-x-jx-docs-pr-2148.jenkins-x.live/community/events/2019-12-dwjw/ is missing some meta data at the top, which is likely the cause of the missing styling

Interesting! I think it will be simpler to just avoid mixing in the metadata with the page content. Let's revert to using the original markdown and having the rich event data not display. Here's a fix.

**Comment by dennisnewel** [comment]
sorry. finally got a chance to take a proper look, and individual pages are already missing something :) it's not a result of the meta information you've added. 
I'll try and fix it and will push the fix into this PR

**Comment by dennisnewel** [comment]
ended up fixing the layout in a different PR, so i just merged in the latest master here to make sure it still worked.

Let's get the metadata out there and get Google to pick it up :) 

/approve

**Pull request merged**
