### PR TITLE
refactor: remove references to static jenkins from component section

### LINKED ISSUE #2933: Remove jenkins references from components section
https://jenkins-x.io/docs/reference/components/decisions/#jenkins and https://jenkins-x.io/docs/reference/components/cloud-native-jenkins/ still talk about serverless/static jenkins. They should be removed

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes #2933

### CODE REVIEW

**Comment by ankitm123** [comment]
The cloud native jenkins section has some buildpack information which could be moved to a different page/section.

**Comment by hferentschik** [comment]
@ankitm123 - there seems to be a broken link:

```
- ./tmp-website/docs/create-project/build-packs/index.html
  *  internally linking to /docs/resources/guides/managing-**/common-tasks/cloud-native-jenkins/, which does not exist (line 0)
     <a href="/docs/resources/guides/managing-**/common-tasks/cloud-native-jenkins/">cloud native Jenkins</a>
htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!
```

**Comment by ankitm123** [comment]
@hferentschik some of the information can be probably added back to the build pack section, but probably better to start fresh. Thoughts? IIRC, @mrageh was working on improving the build pack sections, would like to know what he thinks ...

**Pull request merged**
