### PR TITLE
fix: Update Install jx instructions to auto-detect latest version

### PR DESCRIPTION
**Pull request by juan131**
Signed-off-by: juan131 juan@bitnami.com

---

This PR provides a way to auto-detect the latest version of the `jx` CLI so you don't need to re-deploy the docs whenever you do a release to maintain them up-to-date.

This solution uses the GitHub API and `jq` tool to obtain the latest release. Despite the `jq` is a pretty common tool, and there are other references in these docs to the tool, it's likely users won't have it installed. In case you consider this an issue, consider the workaround below:

```console
curl --silent "https://github.com/jenkins-x/jx/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#'
```

On the other hand, it adds the path to the file to extract (`jx`) to the `tar` instruction to avoid extracting unnecessary file such as the `README.md` or the `changelog.md`.

### CODE REVIEW

**Comment by dennisnewel** [comment]
Is it possible to replace `jq` with something that's more commonly installed on default OSes? seems a bit much to have to install another tool to be able to get the latest version? the `jx version` command will fetch the latest anyway

**Comment by juan131** [comment]
Hi @dennisnewel 

As I mentioned in the description of the PR, there are some alternatives. For instance:

```
curl --silent "https://github.com/jenkins-x/jx/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#'
```

**Comment by dennisnewel** [comment]
@juan131 tried to apply both suggestions and commit back to your branch, but i can't seem to get that to work...ended up with another branch instead: https://github.com/jenkins-x/jx-docs/tree/pr-2003 maybe you could pull from there to update your branch or we could just PR the new branch? (bit of a git beginner here, so not sure if there's an easier way)

**Comment by dennisnewel** [comment]
never mind :) got help to figure out how to push directly to your fork/branch.

We'll see how it looks once the preview environment is up and running

**Comment by juan131** [comment]
Hi @dennisnewel 

I'm sorry I missed your requests!! Thanks so much for adapting the PR!

**Pull request merged**
