### PR TITLE
chore: blog for hacktoberfest 2022

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

# Description

It's that time of the year!

### CODE REVIEW

**Comment by ankitm123** [comment]
We still need to label issues with hacktoberfest label, but cdf wants it by Monday for their blog post!

**Review by rajatgupta24 — APPROVED** [review]
🎉

**Comment by ankitm123** [comment]
> So you should refer to these

Good point, adding them.

> * While issues mainly are placed in jenkins-x/jx the project is encompassed of many repositories in several organisation (you could refer to https://jenkins-x.io/v3/about/overview/source/)

Apart from this, I think a good thing to do with issues labelled for hacktoberfest is to make it clear where the code change can be? For example, if it's an issue related to jx project cli, it will most likely be in jx-project. It's not accurate (as it could be an issue in the dependencies like jx-helpers or go-scm), but can atleast make the life of the new contributor a lot simpler IMO. It's going to overwhelming for new contributors to look at the source documentation and figure out where the change needs to be made. 

Made some changes!

**Comment by msvticket** [comment]
> I think a good thing to do with issues labelled for hacktoberfest is to make it clear where the code change can be? For example, if it's an issue related to jx project cli, it will most likely be in jx-project. It's not accurate (as it could be an issue in the dependencies like jx-helpers or go-scm), but can atleast make the life of the new contributor a lot simpler IMO. It's going to overwhelming for new contributors to look at the source documentation and figure out where the change needs to be made.

I agree

**Review by msvticket — APPROVED** [review]

**Pull request merged**
