### PR TITLE
fix: remove out-dated tutorial for installing jx on gke

### PR DESCRIPTION
**Pull request by dennisnewel**

### CODE REVIEW

**Comment by sharepointoscar** [comment]
I am wondering if it makes more sense to actually update the tutorial rather than deleting it?  I feel folks want tutorials...

**Comment by dennisnewel** [comment]
fair point @sharepointoscar - that would be the best solution. it's not good that we're confusing people though, so i prefer to take it down until we have a new, improved version :)

**Comment by sharepointoscar** [comment]
Let's do it.  We can come up for a new one soon.

**Pull request merged**
