### PR TITLE
chore: Add 'How do I inject Vault secrets...'

### PR DESCRIPTION
**Pull request by silphid**
This is based on my experimentations and understanding, please correct me if I'm wrong! ;)

### CODE REVIEW

**Comment by dennisnewel** [comment]
looks good @silphid !

i'm wondering if it would be better to have a dedicated page under Using Jenkins X -> Developing just about using Vault? We can always expand more on it later

**Comment by Knappek** [comment]
Awesome @silphid , this documentation is needed. Looks good, but after enabling vault in staging/production, it is also possible to inject secrets like you do for the preview environment by simply using the `vault: path/to/mysecret` syntax in your apps repo in `chart/myapp/values.yaml`. Hence you don't need to distinguish between preview and staging/production.

**Comment by silphid** [comment]
@dennisnewel There is already this page about Vault: https://jenkins-x.io/docs/reference/components/vault/  Should I add my documentation at the end?

**Comment by dennisnewel** [comment]
@silphid i think this content is better under the "Using...". Maybe just call it "Using Vault"?

One thing i tried to do with new structure is to split things up between managing and using, with the hope that it'd be easier to find what you're looking for depending on how you use jx; the content itself just hasn't been updated to that yet.

**Comment by silphid** [comment]
Thanks @Knappek, indeed it also works to inject directly into the app's values.yaml. I added a note in that regard! :)

**Pull request merged**
