### PR TITLE
chore: add GitHub action to build image for jx-docs

### PR DESCRIPTION
**Pull request by LinuxSuRen**
# Description

Visit this website is very slow from my country. It'd good to have a docker image. So I can deploy it. I'm considering deploy it to `https://jx.jenkins-zh.cn`.

In order to make sure it works. There're two GitHub secrets needed. They are the username and password (or token) of a GitHub account which can push the images to `ghcr.io`.

* `GHCR_USER`
* `GHCR_TOKEN`

# Checklist:

- [x] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [x] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [x] Any dependent changes have already been merged.

### CODE REVIEW

**Comment by msvticket** [comment]
@LinuxSuRen Is this still something you are interested in?

**Comment by LinuxSuRen** [comment]
hi @msvticket It should work well. I tested it when I created this PR.

**Comment by msvticket** [comment]
What I meant was: Is this still a functionality you are interested in?

Are you still planning on deploying it to https://jx.jenkins-zh.cn?

**Comment by LinuxSuRen** [comment]
I see. I don't have that plan anymore. I guess we could close this now.

**Pull request closed without merging**
