### PR TITLE
fix: moving Labs documentation

### LINKED ISSUE #2842: Improve integration with the Labs documentation
The Labs documentation mixes with the main documentation, in particular, if one uses the search functionality of the site itself. Using search terms like Vault or Boot get the highest-ranking hits in the Labs section which can be confusing to the user. 
Also given that the `jxl` experiment is considered closed I wonder what the purpose is to have the Labs documentation around `jxl` at all. Maybe everything expects the enhancement process could be deleted? 

Here is a list of potential things we could do to improve the situation (in order of preference)

- Delete the `jxl` related Labs docs. This means content under the path of /labs/[jxl|boot|jenkins|wizard]
- Move Labs out of the main Docs part and give it it's own item next to "community" in the header. The idea being of creating a clearer separation between prod docs and labs docs
- Configure the site search to not index the Labs part to at least improve the quality of the search

### PR DESCRIPTION
**Pull request by hferentschik**
* removing jxl related documentation
* moving Labs enhancement pages under community
* updating the weights (order) of the community navigation

fixes #2842

### CODE REVIEW

**Comment by hferentschik** [comment]
@jstrachan, @rawlingsj - what do you think about this change? Given that _jxl_ is not a thing anymore , I think this pull request would clean up a lot of things and reduce confusion.

**Comment by ethangj** [comment]
@vfarcic @MarckK given the conversation on Slack, do you have any objections to this PR?

**Comment by vfarcic** [comment]
No objections from my side

**Comment by hferentschik** [comment]
@ethangj, 'retest' is not configured it seems. 
I am still going to close this PR and open a new one to see whether this 'LGTM analysis' error goes away.

**Pull request closed without merging**
