### PR TITLE
feat: Explain how e2e tests work for jx

### PR DESCRIPTION
**Pull request by fiunchinho**

### CODE REVIEW

**Comment by pmuir** [comment]
Shouldn't this go in the Contributing area?

**Comment by fiunchinho** [comment]
Should we merge Developing and Contributing? BTW, how do I see my changes on the preview environment? they don't seem to show up there.

**Comment by pmuir** [comment]
No, Developing is about using Jenkins X. Contributing is about contributing to Jenkins X.

Developing is poorly named, it might be better as `User Guide`.

>  BTW, how do I see my changes on the preview environment? they don't seem to show up there.

They are there, see http://jx-docs.jx-jenkins-x-jx-docs-pr-1757.infra.jrawlings.co.uk/developing/continuous-integrating-jx-itself/ - I just clicked through the menus to get to that...

**Comment by fiunchinho** [comment]
It seems the content of the website get stored on the browser cache and it needs to clear cache to see latest changes.

I've moved it to contributing.

**Pull request merged**
