### PR TITLE
fix: resolve spacing in Docs section & make toc sidebar sticky

### PR DESCRIPTION
**Pull request by cagiti**
*Before*:
Screenshot 2020-05-04 at 14 42 51

*After*:
Screenshot 2020-05-04 at 14 42 30

------Media view------
*Before* (google image causes page to overscale):
Screenshot 2020-05-04 at 21 25 28

*After*:
Screenshot 2020-05-04 at 21 26 28

-----Add sticky sidebar-----
*Before*:
Screenshot 2020-05-04 at 22 08 26

*After*:
Screenshot 2020-05-04 at 22 07 43

### CODE REVIEW

**Comment by hferentschik** [comment]
>  resolve spacing across website

What URL do I have to look at to see the difference? Trying to understand what this or changes.

**Comment by cagiti** [comment]
> > resolve spacing across website
> 
> What URL do I have to look at to see the difference? Trying to understand what this or changes.

Sorry, should have put WIP on it... was working on this on the side :)

**Comment by hferentschik** [comment]
> Sorry, should have put WIP on it... was working on this on the side :)

No worries. Looks awesome.

**Pull request merged**
