### PR TITLE
fix: link to api-conventions updated

### PR DESCRIPTION
**Pull request by butuzov**
Updated link to api conventions following it's move by
kubernetes/community@06207d23

### CODE REVIEW

**Comment by dennisnewel** [comment]
@jstrachan this stuff is generated i think? do you know where to change the source?

**Comment by pmuir** [comment]
They are generated from the source code that we import. The only way to fix this to update to a kubernetes release that has the links fixed in the source.

**Comment by butuzov** [comment]
Is it possible that something broken in the pipeline process?

For example, I have tracked this line "https://github.com/jenkins-x/jenkins-x-versions/blob/master/jx/scripts/update-jx-website.sh#L52", but  I can't even install `get-crd-api-referrence-docs` to test it... is it possible that apidocs.md isn't actually updating or something?

**Comment by jstrachan** [comment]
I wonder if these URLs come from the specific version of the k8s API we build jx against?

**Comment by butuzov** [comment]
I believe they come from https://github.com/jenkins-x/jx/blob/d8c3e032e903b54c39b5c9d775dd09a6b3eb6af0/Makefile.codegen#L60:L73, but I can't build, but I wasn't able to perform step `install-refdocs`, as some of the conflicts happened during go modules pulling. didn't go further...

**Comment by hferentschik** [comment]
Closing this pull request, since the fix needs to happen on the code generation side.

**Pull request closed without merging**
