### PR TITLE
docs: add help for stuck install

### PR DESCRIPTION
**Pull request by arpad9**
Signed-off-by: David A. Urban <arpad9@gmail.com>

Fixes https://github.com/jenkins-x/jx-docs/issues/2998

### CODE REVIEW

**Comment by ankitm123** [comment]
@arpad9 I think it should be in the `set up and install` faq section, wdyt? This page: https://jenkins-x.io/docs/resources/faq/setup/

**Comment by arpad9** [comment]
@ankitm123 I can move it if you like, let me know.  But, this is my case:
I was thinking that it was more of a troubleshooting step.  I only know of two instances of this happening so far.
Also, if it keeps happening, I'd call it a bug, not a feature of installing.  :-)

**Comment by arpad9** [comment]
You know... yes... it's still in faq.  I'll move it.

**Comment by arpad9** [comment]
Well... though... this is happening on existing installs.  IDK.  I'm torn.  Let me know.

**Comment by arpad9** [comment]
Updated

**Comment by ankitm123** [comment]
> Also, if it keeps happening, I'd call it a bug, not a feature of installing. :-)
Yeah, I will check the code, and try to figure our the logic for this 👍

**Pull request merged**
