### PR TITLE
K3s - added new page for installing Vault inside Kubernetes

### PR DESCRIPTION
**Pull request by babadofar**
# Description

Installing Jenkins X on a developer laptop should be easier. Adding a new page with instructions on how to install Vault inside of Kubernetes. This requires this [PR](https://github.com/jx3-gitops-repositories/jx3-k3s-vault/pull/3) to be merged first

Fixes [#8106 (issue)](https://github.com/jenkins-x/jx/issues/8106)

### CODE REVIEW

**Comment by ankitm123** [comment]
Rebase with the latest main branch, else it will be pending forever.

**Comment by ankitm123** [comment]
If helmfile sync works, I think this is the better approach, I will close my PR.

**Comment by babadofar** [comment]
rebased...

**Pull request closed without merging**
