### PR TITLE
docs: Create 2020-cdcon.md

### PR DESCRIPTION
**Pull request by zestyroxy**
Here's a blog post to promote the Jenkins X talks at CDCon.

I'm not sure where to upload this image? 
cdcon-register

### CODE REVIEW

**Comment by rawlingsj** [comment]
Hi @zestyroxy - thanks for the PR, the build failed with this error...
```
- ./tmp-website/blog/2020/09/16/cdcon2020/index.html
  *  internal image /assets/images/cdcon-register.png does not exist (line 0)
```
also it's worth amending the commit message so that `Semantic Pull Request ` passes, having a prefix of `docs:` should sort it.

**Comment by zestyroxy** [comment]
Thanks @rawlingsj --I'm not sure where to upload the image. Can you point me to the right place?

**Comment by ankitm123** [comment]
@zestyroxy The images can go here: https://github.com/jenkins-x/jx-docs/tree/master/static/images.
You can then reference the image as `/images/<name of the image>`.

**Comment by zestyroxy** [comment]
thanks @ankitm123 but I don't have upload access.
Uploads are disabled.

File uploads require push access to this repository.

**Comment by ankitm123** [comment]
You can just add it to git (the same way you added the file - `2020-cdcon.md`) as part of this PR. I can make a PR adding this file if you want. Dont have to upload anything.

**Pull request merged**
