### PR TITLE
fix : Modified path create-cluster to /docs/getting-started/setup/create-cluster

### PR DESCRIPTION
**Pull request by chandanikumari**
Author: Chandani Kumari, Committer: Chandani Kumari <chandanikumari92@gmail.com>

### CODE REVIEW

**Comment by MarckK** [comment]
Awesome work, @chandanikumari!

We have a  中文 translation of the site. You can view it as an option under the languages section (the tab labelled `English` in the top nav bar). 

It would be fantastic of you to make the proposed link change to the 中文 versions of the site, similar to PR #2010.

**Comment by chandanikumari** [comment]
@MarckK Its done and PR is raised :)

**Pull request merged**
