### PR TITLE
docs: contributing Spring Boot content back to OSS docs

### PR DESCRIPTION
**Pull request by jha-cloudbees**
* Enhanced Intro
* Procedure for using existing Spring Boot project into Jenkins X using `jx import`
* Procedure for creating new Spring Boot project using `jx create spring`
* Changes to files created/changed when running the above procedures.

### CODE REVIEW

**Comment by jha-cloudbees** [comment]
ping @dennisnewel and @sharepointoscar. Spring boot content enhancement.

**Comment by jha-cloudbees** [comment]
@jstrachan it seems I may have mucked up this rebased PR. Didn't mean to slurp in all of these commits! Al I did was run `git pull --rebase upstream master` in the jha-cjxd2oss-6 branch and it made a mess of things. The other PR #1930 went cleanly I think.

**Comment by dennisnewel** [comment]
@jha-cloudbees should we close this one since #1997 includes the same fixes?

**Comment by jha-cloudbees** [comment]
Yep, thanks @dennisnewel! Closing.

**Pull request closed without merging**
