### PR TITLE
[WiP] New site structure + theme

### PR DESCRIPTION
**Pull request by dennisnewel**
This is the new structure as suggested in https://github.com/jenkins-x/jx/issues/5157 with the new Docsy (https://docsy.dev) Hugo theme as well.

### CODE REVIEW

**Comment by MarckK** [comment]
Hi @dennisnewel, 
To make sure my commits are linking to my GitHub account (currently they are oddly all greyed out), I wanted to check the metadata on them. 

I went through the commit history on the branch for this PR, and I couldn't see any of my commits for my work (https://github.com/jenkins-x/jx-docs/pull/1891) in the git logs. I know you said that working off your branch was easier for you than working off my branch and that is why you moved my rebuild onto your branch.

That's fine, but not having my work show up in the git history is problematic. Any ideas on why my commits aren't there?

Screenshot 2019-09-09 at 08 36 29

**Comment by dennisnewel** [comment]
that's weird @MarckK. I moved out all the files from the old site, merged in your branch, and then moved the files back in to the `/old` folder. Not sure why your changes have not been included 🤔 though now you mention it, i remember i removed the Norwegian language at some point...

we could likely try and cherry-pick some of your changes if you know some of it is missing?

**Comment by MarckK** [comment]
Hi @dennisnewel,
You imported all of my work at commit https://github.com/jenkins-x/jx-docs/pull/1911/commits/3c1ac3ada74530f2ecc1652e0c955c95c459e814. However, you copied over the content of my repo, but not its git history, thereby erasing attribution of my work:
Screenshot 2019-09-10 at 07 31 57

**Comment by sharepointoscar** [comment]
I suppose that happened with my contribution as well...

Sent from my iPhone X

On Sep 9, 2019, at 11:45 PM, Kara de la Marck <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @dennisnewel<https://github.com/dennisnewel>,
You imported all of my work at commit 3c1ac3a<https://github.com/jenkins-x/jx-docs/commit/3c1ac3ada74530f2ecc1652e0c955c95c459e814>. However, you copied over the content of my repo, but not its git history, thereby erasing attribution of my work:
[Screenshot 2019-09-10 at 07 31 57]<https://user-images.githubusercontent.com/15032115/64589993-67b94780-d39e-11e9-8f38-6ca72b796813.png>

**Comment by dennisnewel** [comment]
So sorry @MarckK and @sharepointoscar 😞 that was absolutely not my intention. I was trying 17 different ways to keep the old files, but move them out of the way, that i must has seriously messed up the git history.

I'll go through the individual commits to make sure all your changes are in. 

And i'll try not to be too fancy with git again...obviously not my strong side.

**Comment by MarckK** [comment]
@dennisnewel, re your message [_index2.html](https://github.com/jenkins-x/jx-docs/blob/site-restructure/content/en/about/_index2.html) can be taken out. 

I was playing with different formats for the About page, and that was the default format given by Docsy for the page. In the end I preferred using a more formal style, having it look more like a regular documentation page.

**Comment by dennisnewel** [comment]
this PR resolves jenkins-x/jx#5157

**Pull request merged**
