### PR TITLE
[wip] docs: Deleting deprecated content related to Jenkins

### LINKED ISSUE #2874: Deprecated Content: Custom Jenkins Servers
This is no longer relevant. https://jenkins-x.io/docs/reference/components/custom-jenkins/

### PR DESCRIPTION
**Pull request by sharepointoscar**
The content on this page is no longer relevant.  Closes #2874

### CODE REVIEW

**Comment by sharepointoscar** [comment]
@abayer I think this content is deprecated, but can you confirm?  I see other pages linking to it, hence why the HTMLProofer failed.

Before I remove the links from other pages, I'd like to confirm this is really outdated content.

**Comment by ethangj** [comment]
@abayer does this look good to you?

**Comment by abayer** [comment]
Yup, looks right to me.

**Comment by hferentschik** [comment]
To get this PR in, the broken links need to be fixed first:

```
- ./tmp-website/about/overview/changelog/index.html
  *  internally linking to /docs/resources/guides/managing-**/common-tasks/custom-jenkins/, which does not exist (line 0)
     <a href="/docs/resources/guides/managing-**/common-tasks/custom-jenkins/">custom Jenkins server</a>
- ./tmp-website/docs/reference/components/lighthouse/index.html
  *  internally linking to /docs/resources/guides/managing-**/common-tasks/custom-jenkins/, which does not exist (line 0)
     <a href="/docs/resources/guides/managing-**/common-tasks/custom-jenkins/">Custom Jenkins Server App</a>
- ./tmp-website/docs/resources/guides/managing-**/old/manage-via-gitops/index.html
  *  internally linking to /docs/resources/guides/managing-**/common-tasks/custom-jenkins/, which does not exist (line 0)
     <a href="/docs/resources/guides/managing-**/common-tasks/custom-jenkins/">custom Jenkins servers</a>
htmlproofer 3.15.3 | Error:  HTML-Proofer found 3 failures!
```

**Comment by ethangj** [comment]
@sharepointoscar once you clean those links up lemme know I'll and re-approve

**Comment by sharepointoscar** [comment]
> @sharepointoscar once you clean those links up lemme know I'll and re-approve


@ethangj I've fixed those 3 bad links...

**Pull request merged**
