### PR TITLE
Viktor's talks

### PR DESCRIPTION
**Pull request by vfarcic**

### CODE REVIEW

**Comment by MarckK** [comment]
@dennisnewel We have a lot of talks listed in the "Talks and Conferences" section under "Getting Started" that don't have recordings of the talks. That page is mostly functioning as a calendar list of talks already given, some with brief abstracts. 

This shows people are talking about Jenkins X and that the community is active, but isn't really useful for people looking for talks to help them with getting started. I propose moving this page to a "Talks and Conferences" section under community section. While leaving those talks that are recorded in this "Talks and Conferences" section, as useful resource for individuals looking for talks to watch to help them with getting started.

**Comment by MarckK** [comment]
@vfarcic Thank you for your PR!

Would you mind changing the path for your additions so that they are added to this file: `jx-docs/content/en/community/talksdemos/_index.md`. Your additions will then show here: https://jenkins-x.io/community/talksdemos/  We are listing all future, current, past talks and demos there.

If any of your talks are recorded, please add them to the talks.md file in the 'getting started' directory. We'll be cleaning up that file over the next few days and removing any talks that don't have linked recordings. This is to more easily surface recorded talks and demos to those looking for resources under 'getting started'.

**Comment by dennisnewel** [comment]
sorry @MarckK, this fell off my radar when it was closed :) i'll create a separate ticket for your idea - makes a lot of sense to me

**Pull request merged**
