### PR TITLE
docs: add blog post for the jx-pipelines-visualizer

### PR DESCRIPTION
**Pull request by vbehar**
@MarckK @rawlingsj @jstrachan what do you think?

### CODE REVIEW

**Comment by rawlingsj** [comment]
looks like dns was a bit slow to resolve, I can see the blog here, looks good, will retrigger CI to be sure
http://jx-docs.jx-jenkins-x-jx-docs-pr-3073.jenkins-x.live/blog/2020/09/23/jx-pipelines-visualizer/

/retest

**Comment by rawlingsj** [comment]
though I wonder if we need to make the embedded youtube video fit into a smaller area?  
/hold

**Comment by rawlingsj** [comment]
well it looks ok, if you want to reduce it we can always do that in a followup PR
/hold cancel

**Comment by vbehar** [comment]
awesome, thanks. Yes I re-used the embed from another blog post, but I'll make another PR to make it smaller

**Pull request merged**
