### PR TITLE
fix: [Docs/Bug] Mobile view updated

### LINKED ISSUE #3313: Mobile view
**This is a Bug Report**
Hey, I was going through the site & I noticed that the site is not mobile-friendly at all.

**Problem:**
image

**Proposed Solution:**
I'd like to work on the mobile view of the site to make it mobile-friendly using the media queries.

**Page to Update:**
https://jenkins-x.io/docs/....

**Steps to Reproduce:**
Visit: https://jenkins-x.io/ 
(on mobile)

### PR DESCRIPTION
**Pull request by amino19**
_Signed-off-by: amino19  <anshumaankrprasad76@gmail.com>_

# Description
Commit update the site to be "mobile-friendly"

Fixes #3313  (issue)

# Checklist:

- [x] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [x] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ ] Any dependent changes have already been merged.

### CODE REVIEW

**Comment by amino19** [comment]
@ankitm123 : Pl review this! :slightly_smiling_face:

**Comment by amino19** [comment]
@jstrachan : Thanks to be here, just saw preview has fixed the issue!

**Comment by amino19** [comment]
### Desktop mode:

**Comment by aminoxix** [comment]
closes #2960

**Pull request merged**
