### PR TITLE
docs: First translate to 'ja' for index.html

### PR DESCRIPTION
**Pull request by silverskyvicto**
#2473 

I translated the first page into Japanese.

### CODE REVIEW

**Comment by ankitm123** [comment]
@MarckK @jstrachan @rawlingsj thoughts?

**Comment by ankitm123** [comment]
btw @silverskyvicto since we are moving to jx3, it would be awesome to look at translating jx3 (may not be now, but in the long term). https://jenkins-x.io/docs/v3/

**Comment by silverskyvicto** [comment]
@ankitm123 

I haven't included it in the pull request, but I'm slowly working on translating the jx3 documentation.

**Comment by MarckK** [comment]
Thank you for your PR @silverskyvicto. We are going to be undergoing a number of changes for the Jenkins X v3 release. Given this is the case, it may be better to resume translation in the coming months, towards 2021.

**Comment by silverskyvicto** [comment]
@MarckK 

So the changes will be made.

I was translating the existing Jenkins X v3 documentation.
I'll think about the v2 one when v3 is all done.

**Comment by msvticket** [comment]
It seems like this was abandoned. I don't see any point in merging something incomplete, that will only annoy any potential readers.

**Pull request closed without merging**
