### PR TITLE
docs: Added a note to wait for the commands to complete.

### PR DESCRIPTION
**Pull request by jjasghar**
Added a fun note to quickstart guide to enforce _waiting_ for the pipelines to complete.

/cc @a-roberts

### CODE REVIEW

**Comment by MarckK** [comment]
Hi @jjasghar , Thank you for your PR.

Please amend your commit by prefixing its heading and its commit message with "docs:" and signing the commit. Thank you.

**Comment by jjasghar** [comment]
I've updated it, but it says there's a conflict :'( any advice here?

**Comment by hervelemeur** [comment]
@jjasghar go in your forked repository folder, then

```
git remote add upstream https://github.com/jenkins-x/jx-docs
git pull upstream master # To retrieve last commits from jenkins-x/jx-docs
git checkout patch-1
git merge master
# there should be a conflict here, resolve it then commit your merge conflict fix and push it
```

**Comment by msvticket** [comment]
File doesn't exist anymore

**Pull request closed without merging**
