### PR TITLE
feat: switch to docsy go module

### LINKED ISSUE #3516: switch to docsy go module
**This is a Feature Request**

https://github.com/google/docsy/discussions/535

Switch to go modules for docsy instead of git submodules.

### PR DESCRIPTION
**Pull request by aabhas-sao**
Signed-off-by: Aabhas Sao <aabhassao0@gmail.com>

# Description

Added docsy theme as a go module and removed docsy as git submodules.

Fixes #3516
# Checklist:

- [x] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [x] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [x] Any dependent changes have already been merged.

### CODE REVIEW

**Comment by aabhas-sao** [comment]
Hey @ankitm123,

please have a look at this PR.
/assign @ankitm123

**Comment by ankitm123** [comment]
Does it build locally? I will check this weekend.

**Comment by aabhas-sao** [comment]
> Does it build locally? I will check this weekend.

Yes it builds successfully. Tested both ways - make server and make compose-up.

**Pull request merged**
